### PR TITLE
feat: Pypi publish ghub actions

### PR DESCRIPTION
**Pull request by software-dov**

### CODE REVIEW

**Review by busunkim96 — APPROVED** [review]
Not sure if it's already the case, but if possible please use an [API token](https://pypi.org/help/#apitoken)

**Comment by software-dov** [comment]
I have the environment setup with an API token. Whether it works is another issue :p

**Comment by software-dov** [comment]
@0x2b3bfa0 and here too please :P
This is totally my fault. Thank you for contributing to the project! It's so nice to see that other people use it.

**Comment by 0x2b3bfa0** [comment]
@googlebot I consent.

**Pull request merged**
