### PR TITLE
fix: update docstring to match type hint

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
@googlebot I signed it!

**Review by software-dov — APPROVED** [review]
Nice catch!

**Comment by busunkim96** [comment]
What do you have to do to get circleci to run for external folks? @software-dov

**Comment by software-dov** [comment]
> What do you have to do to get circleci to run for external folks? @software-dov

I'm really not sure. It shouldn't matter if the PR is internal or external. I'm going to try making a trivial change and see if that triggers it.

**Comment by 0x2b3bfa0** [comment]
Houston, we have a problem! 🔔 &nbsp;@busunkim96 & @software-dov.

**Pull request merged**
