### PR TITLE
chore: Ci fix

### PR DESCRIPTION
**Pull request by software-dov**

### CODE REVIEW

**Comment by software-dov** [comment]
@0x2b3bfa0 Could you please add a comment that contains the text
@googlebot I consent.
?
I've screwed up somehow during CI transition, and now other PRs are blocked. Thanks so much in advance.

**Comment by 0x2b3bfa0** [comment]
@googlebot I consent.

**Comment by 0x2b3bfa0** [comment]
You're welcome! 😊

**Comment by software-dov** [comment]
Thanks so much.

**Review by arithmetic1728 — APPROVED** [review]

**Pull request merged**
